sudo: false
language: node_js
node_js:
  - "8"

notifications:
  email: evenchange4@gmail.com

script:
  - yarn run eslint
  - yarn run test
  - yarn run build
  - yarn run build-storybook

after_success:
  - ./node_modules/.bin/codecov

cache:
  yarn: true
  directories:
    - node_modules
