// flow-typed signature: 6c072e045f443fbfb99ea7bf3d5d8b5f
// flow-typed version: <<STUB>>/github-changes_v1.1.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github-changes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'github-changes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'github-changes/bin/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'github-changes/bin/index.js' {
  declare module.exports: $Exports<'github-changes/bin/index'>;
}
